

ANS_LOG="ans-log.txt"
touch "$ANS_LOG"
function question() {
    QUESTION="$1"
    EXAMPLE="$2"

    printf "$QUESTION ans> "
    read ANS
    echo "example: $EXAMPLE"
    echo "$ANS" >> "$ANS_LOG"
}

question "sudo ?" "他のユーザーとしてコマンドを実行するための認証管理ユーティリティ"
question "ufw ?" "ファイアウォールを管理するためのコマンドラインユーティリティ"
question "ssh ?" "クライアントとサーバー間の安全な通信のためのネットワークプロトコル"
question "sshd ?" "セキュアなリモートログインとコマンド実行を可能にするサーバーソフトウェア"
question "systemctl ?" "systemdおよびサービスを制御するユーティリティ"
question "service ?" "システムサービスを管理するユーティリティ"
question "addgroup ?" "システムに新しいグループを追加するコマンド"
question "adduser ?" "システムに新しいユーザーを追加するコマンド"
question "usermod ?" "ユーザーアカウントを変更するコマンド"
question "lsblk ?" "パーティションを含むブロックデバイスをリストするコマンド"
question "aptitude ?" "Debianベースのシステム向けの高レベルのパッケージマネージャー"
question "apt ?" "パッケージを管理するためのコマンドラインユーティリティ"
question "passwd ?" "ユーザーのパスワードを変更または設定するコマンド"
question "sestatus ?" "SELinuxのステータスを確認するコマンド"
question "aa-status ?" "AppArmorのステータスを確認するコマンド"
question "firewalld ?" "ファイアウォール構成を管理するための動的なファイアウォールマネージャー"
question "dpkg ?" "Debianベースのシステム向けのパッケージマネージャー"
question "cron ?" "タスクを特定の時間に自動的に実行するためのユーティリティ"
question "crontab ?" "タスクのスケジュールを表示または編集するためのコマンド"
question "shasum ?" "SHAチェックサムを計算および検証するコマンド"

question "uname ?" "システム情報を表示するコマンド"
question "grep ?" "テキスト内のパターンを検索するためのコマンドラインユーティリティ"
question "sort ?" "テキストファイルの行をソートするコマンド"
question "wc ?" "テキストやファイルの行数、単語数、文字数をカウントするコマンド"
question "free ?" "システムのメモリ情報を表示するコマンド"
question "printf ?" "書式化された出力を生成するコマンド"
question "awk ?" "テキスト処理やパターン検索に使用されるプログラム言語"
question "df ?" "ディスク使用状況を表示するコマンド"
question "tail ?" "ファイルの末尾を表示するコマンド"
question "top ?" "システムのリソース使用状況をリアルタイムで表示するコマンド"
question "sed ?" "テキストの編集や変換を行うためのストリームエディタ"
question "python3 ?" "Pythonのバージョン3を実行するためのコマンド"
question "who ?" "現在ログインしているユーザーを表示するコマンド"
question "hostname ?" "ホスト名を表示または設定するコマンド"
question "ip ?" "ネットワークインターフェースの情報を表示するコマンド"
question "cat ?" "ファイルの内容を表示するコマンド"
question "wall ?" "全ユーザーにメッセージを送信するコマンド"
